### ISSUE TITLE
Drop python 3.6 support

### ISSUE THREAD

**Issue by saroad2** [click-contrib/click_params#11]
Description
========

On December 23rd 2021 Python 3.6 has reach its End-of-Life date.
Therefore *click-params* should no longer support that version.

**Comment by lewoudar** [comment]
I just looked at the click project. On [pypi](https://pypi.org/project/click/) it seems that python3.6 is still supported but.. when I look at the [code](https://github.com/pallets/click/commit/dd3e108b36da58591c52763cfe8e5d7c26823bf6) it is a matter of time before they drop python3.6 support, so yeah we can do it too. I will create a PR for that, thanks for the reminder :)
