### ISSUE TITLE
`ListParamType` should treat empty strings as empty list

### ISSUE THREAD

**Issue by saroad2** [click-contrib/click_params#13]
Description
========

When `ListParamType` try to convert an empty string it creates a list with one empty item.
The more logical use case is that empty string should be converted to an empty list.

Code example
=========

```python
import click
import click_params

my_list = click.prompt(
    "Strings list",
    default="",
    type=click_params.StringListParamType(),
    show_default=False,
)
print(my_list)
```

Output:
```
Strings list: 
['']
```

My suggestion
==========

I would like to suggest a boolean parameter for `ListParamType` called `ignore_empty` that will do just that, handle empty string as empty list. This parameter will be false by default in order to keep backward compatibility.

In the example above, the code will be changed to:
```python
my_list = click.prompt(
    "Strings list",
    default="",
    type=click_params.StringListParamType(ignore_empty=True),
    show_default=False,
)
print(my_list)
```

And the output will be:
```
Strings list: 
[]
```

**Comment by saroad2** [comment]
Already on it 😊

**Comment by lewoudar** [comment]
Thanks a lot! I will look at it this week.
